"""IndexRecord.custom_date_section

Revision ID: 4bef8446b252
Revises: b534668d3fa1
Create Date: 2022-12-31 16:34:48.929875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bef8446b252'
down_revision = 'b534668d3fa1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_record', sa.Column('custom_date_section', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_record', 'custom_date_section')
    # ### end Alembic commands ###
