"""Release/IndexRecord nton

Revision ID: 19d09ecb6c4c
Revises: 4bef8446b252
Create Date: 2023-01-01 09:33:21.638636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d09ecb6c4c'
down_revision = '4bef8446b252'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_no', sa.Text(), nullable=True),
    sa.Column('release_dir', sa.Text(), nullable=True),
    sa.Column('file', sa.Text(), nullable=True),
    sa.Column('external_urls', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release'))
    )
    op.create_table('index_record_releases',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['index_record.id'], name=op.f('fk_index_record_releases_left_id_index_record')),
    sa.ForeignKeyConstraint(['right_id'], ['release.id'], name=op.f('fk_index_record_releases_right_id_release')),
    sa.PrimaryKeyConstraint('left_id', 'right_id', name=op.f('pk_index_record_releases'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_record_releases')
    op.drop_table('release')
    # ### end Alembic commands ###
