"""Release model/relation

Revision ID: 897e9536d86a
Revises: 4bef8446b252
Create Date: 2022-12-31 22:11:35.567455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897e9536d86a'
down_revision = '4bef8446b252'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_no', sa.Text(), nullable=True),
    sa.Column('release_dir', sa.Text(), nullable=True),
    sa.Column('file', sa.Text(), nullable=True),
    sa.Column('external_urls', sa.JSON(), nullable=True),
    sa.Column('index_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['index_record_id'], ['index_record.id'], name=op.f('fk_release_index_record_id_index_record')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release')
    # ### end Alembic commands ###
