"""ReleasePage and PlayerFile

Revision ID: d2c603fd41c4
Revises: 19d09ecb6c4c
Create Date: 2023-01-01 11:16:42.287661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c603fd41c4'
down_revision = '19d09ecb6c4c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], name=op.f('fk_release_page_release_id_release')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_page'))
    )
    op.create_table('player_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=True),
    sa.Column('release_page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_page_id'], ['release_page.id'], name=op.f('fk_player_file_release_page_id_release_page')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_file'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_file')
    op.drop_table('release_page')
    # ### end Alembic commands ###
