"""ReleasePage: distinct content/custom_body

Revision ID: 7e8cedf87b8b
Revises: d2c603fd41c4
Create Date: 2023-01-01 12:08:09.836839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8cedf87b8b'
down_revision = 'd2c603fd41c4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release_page', sa.Column('content', sa.Text(), nullable=True, comment='Page content to be embedded in layout. Imported from pr-text.inc.php.'))
    op.add_column('release_page', sa.Column('custom_body', sa.Text(), nullable=True, comment='Full page content for the release pages that have an index.html.'))
    op.drop_column('release_page', 'body')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release_page', sa.Column('body', sa.TEXT(), nullable=True))
    op.drop_column('release_page', 'custom_body')
    op.drop_column('release_page', 'content')
    # ### end Alembic commands ###
