"""PlayerFile: add number

Revision ID: 83b819ef76cf
Revises: 7e8cedf87b8b
Create Date: 2023-01-01 13:21:40.260857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b819ef76cf'
down_revision = '7e8cedf87b8b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_file', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_file', 'number')
    # ### end Alembic commands ###
