"""Release: external_urls-->release_data

Revision ID: a3080985f3e8
Revises: 83b819ef76cf
Create Date: 2023-01-03 00:22:58.907747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a3080985f3e8'
down_revision = '83b819ef76cf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('release_data', sa.JSON(), nullable=True))
    op.drop_column('release', 'external_urls')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('external_urls', sqlite.JSON(), nullable=True))
    op.drop_column('release', 'release_data')
    # ### end Alembic commands ###
