"""ReleasePage.custom_tracklist

Revision ID: bd8b43606410
Revises: a3080985f3e8
Create Date: 2023-01-05 18:18:57.091529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8b43606410'
down_revision = 'a3080985f3e8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release_page', sa.Column('custom_tracklist', sa.Text(), nullable=True, comment='Some releases have a list.inc.php file.'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release_page', 'custom_tracklist')
    # ### end Alembic commands ###
