volumes:
  db_data:
    driver: local


services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pyramidprj
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
