module.exports = [
    // 'mi-croevkhas/sunhigh-and-trenchlow',  // dev has correct durations
    // 'indu-mezu/noisiki',  // dev doesn't render reviews
    // 'hertzcanary/birds-just-wanna-have-fun-fun-fun',  // dev renders header icons and special chars correctly
    // 'lee-rosevere/symphony-for-monotron',  // dev doesn't render `Appearance` and `Related Movement` sections
    'hertzcanary/why-do-birds-sing-so-gay',
    'the-hairy-giant/cautionary-adhesive',
    'noisesurfer/old-autumn-tales-ep',
    'c4/vibe-from-the-korg-electribe',
    'sylver-second/glitchy-attitudes',
    'hertzcanary/birds-dont-come-easy',
    'june-lauren-prescott/hitting-30-for-the-first-time',
    'c4/journey-to-the-centre-of-your-mind',
    'clockwork-keyboard/clock-soup-for-cooked-airports',
    'overthruster/revursals',
    'the-hardliner/suicide-bag-safely-locked-away',
    'graffiti-mechanism/in-vitro',
    'jacker-seppeli/das-isch-no-musig',
    'mono-syntax/echo',
    'thrust-pomp/very-cool-party',
    'stereo-realist/stereo-realist',
    'black-boss/hood-stories',
    'd_ruffnik/hatred',
    'john-geilo/charles-is-in-da-house',
    'sergio-stallone/saldi',
    'origami-repetika/jamboree-train',
    'toxic-chicken/things',
    'q24/vol1',
    'breschniev-and-mech/benchmarked-v2',
    'surrogate-sigma/the-monarc',
    'c4/subterranean-by-design',
    'pablo-javier-piacente/profundidad-del-tiempo',
    'karambol-bolno/b0ln0',
    'thrust-pomp/fucker',
    'holorime/2-cig',
    'duality-micro/batteries-low-ep',
    'jkp/film-noir',
    'matri-oxar/tiholaz-playing-the-piano-for-five-minutes',
    'origami-repetika/a-friend-in-space-and-time',
    'kai-nobuko/typical-trip',
    'slowfreq/tunnel',
    'slow-wave-sleep/elogio-della-follia',
    'origami-repetika/wonder-and-suspicion-in-cryptomnesia',
    'mauk-tenieb/esiön',
    'surrogate-sigma/untitled',
    'unseq/subject_xi',
    'origami-repetika/frozen-desert',
    'diobati-tanpa/diobati-tanpa',
    '20y20k',
]