def includeme(config):
    config.add_static_view("static", "static", cache_max_age=3600)
    config.add_route("home", "/")
    config.add_route("index2", "/index2.htm")
    config.add_route("Releases", "/Releases/{rlsdir}/")
    config.add_route("Releases_with_subdir", "/Releases/{rlsdir}/{subdir}/")

    config.add_route("create_release", "/create_release/")
    config.add_route("request_preview", "/request_preview/")
    config.add_route("preview_release", "/preview_release/{file}/")
    config.add_route("request_upload", "/request_upload/")
    config.add_route("check_upload", "/check_upload/{file}/")
    config.add_route("commit_release", "/commit_release/")
    config.add_route("request_iaupload", "/request_iaupload/")
    config.add_route("check_iaupload", "/check_iaupload/{file}/")

    config.add_route("release_list", "/releases/")
    config.add_route("Release_list", "/Releases/")
    config.add_route("release_edit", "/edit/{release_id}/")
    config.add_route("update_release", "/update_release/")

    config.add_route("index_record_list", "/index_records/")
    config.add_route("delete_index_record", "/index_records/{index_record_id}/")
    config.add_route("index_record_edit", "/edit_index_record/{index_record_id}/")
    config.add_route("upsert_index_record", "/upsert_index_record/")
    config.add_route("index_record_create", "/create_index_record/")
